//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentSite4.Report
{
    public partial class ImportHierarchy
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlUpload;
        protected global::System.Web.UI.WebControls.DropDownList ddlDistributor;
        protected global::System.Web.UI.WebControls.DropDownList ddlAgentClone;
        protected global::System.Web.UI.WebControls.DropDownList ddlPlayerTemplateAgent;
        protected global::System.Web.UI.WebControls.DropDownList ddlPlayerClone;
        protected global::System.Web.UI.WebControls.CheckBox chkCloneAgentRights;
        protected global::System.Web.UI.WebControls.FileUpload fuHierarchy;
        protected global::System.Web.UI.WebControls.Button btnUpload;
        protected global::System.Web.UI.WebControls.Button btnDownloadExample;
        protected global::System.Web.UI.WebControls.Panel pnlResults;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblTotalAgents;
        protected global::System.Web.UI.WebControls.Label lblInvalidAgents;
        protected global::System.Web.UI.WebControls.Label lblDuplicateAgents;
        protected global::System.Web.UI.WebControls.Label lblTotalPlayers;
        protected global::System.Web.UI.WebControls.Label lblInvalidPlayers;
        protected global::System.Web.UI.WebControls.Label lblDuplicatePlayers;
        protected global::System.Web.UI.WebControls.Label lblBatchId;
        protected global::System.Web.UI.WebControls.DropDownList ddlDuplicateAffixMode;
        protected global::System.Web.UI.WebControls.TextBox txtDuplicateAffix;
        protected global::System.Web.UI.WebControls.Button btnRevalidate;
        protected global::System.Web.UI.WebControls.Button btnMassFix;
        protected global::System.Web.UI.WebControls.Button btnNewImport;
        protected global::System.Web.UI.WebControls.Button btnShowDuplicates;
        protected global::System.Web.UI.WebControls.Button btnShowRowsToFix;
        protected global::System.Web.UI.WebControls.Button btnShowAllRows;
        protected global::System.Web.UI.WebControls.Label lblCurrentFilter;
        protected global::System.Web.UI.WebControls.GridView gvAgents;
        protected global::System.Web.UI.WebControls.GridView gvPlayers;
    }
}
